import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";

import Footer from "@/components/Footer";
import AllNavsection from "@/components/AllNavsection";
import { ToastContainer } from "react-toastify";

const geistSans = Noto_Serif_Bengali({

  subsets: ["latin", "bengali"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#F0F5F0]">
       <AllNavsection/>
       <ToastContainer/>

        <main className="container  mx-auto  ">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
